### PR TITLE
Windows support

### LINKED ISSUE #13: Fails to build on Windows
```
   Compiling libcec-sys v3.0.0
error: failed to run custom build command for `libcec-sys v3.0.0`

Caused by:
  process didn't exit successfully: `C:/Users/nicky/Documents/crate_targets\debug\build\libcec-sys-bb45cac0d70fb383\build-script-build` (exit code: 101)
  --- stdout
  cargo:rerun-if-changed=build.rs
  cargo:lib_vendored=true
  cargo:libcec_version_major=4
  cargo:rustc-cfg=abi4
  Building libcec from local source
  cmake platform
  CMAKE_TOOLCHAIN_FILE_x86_64-pc-windows-msvc = None
  CMAKE_TOOLCHAIN_FILE_x86_64_pc_windows_msvc = None
  HOST_CMAKE_TOOLCHAIN_FILE = None
  CMAKE_TOOLCHAIN_FILE = None
  CMAKE_GENERATOR_x86_64-pc-windows-msvc = None
  CMAKE_GENERATOR_x86_64_pc_windows_msvc = None
  HOST_CMAKE_GENERATOR = None
  CMAKE_GENERATOR = None
  CMAKE_PREFIX_PATH_x86_64-pc-windows-msvc = None
  CMAKE_PREFIX_PATH_x86_64_pc_windows_msvc = None
  HOST_CMAKE_PREFIX_PATH = None
  CMAKE_PREFIX_PATH = None
  CMAKE_x86_64-pc-windows-msvc = None
  CMAKE_x86_64_pc_windows_msvc = None
  HOST_CMAKE = None
  CMAKE = None
  running: "cmake" "C:/Users/nicky/Documents/crate_targets\\debug\\build\\libcec-sys-e405de6718a35383\\out\\vendor\\src\\platform" "-G" "Visual Studio 17
2022" "-Thost=x64" "-Ax64" "-DCMAKE_INSTALL_PREFIX=C:/Users/nicky/Documents/crate_targets\\debug\\build\\libcec-sys-e405de6718a35383\\out\\platform_build"
 "-DCMAKE_C_FLAGS= -nologo -MD -Brepro" "-DCMAKE_C_FLAGS_DEBUG= -nologo -MD -Brepro" "-DCMAKE_CXX_FLAGS= -nologo -MD -Brepro" "-DCMAKE_CXX_FLAGS_DEBUG= -n
ologo -MD -Brepro" "-DCMAKE_ASM_FLAGS= -nologo -MD -Brepro" "-DCMAKE_ASM_FLAGS_DEBUG= -nologo -MD -Brepro" "-DCMAKE_BUILD_TYPE=Debug"
  -- Configuring done
  -- Generating done
  -- Build files have been written to: C:/Users/nicky/Documents/crate_targets/debug/build/libcec-sys-e405de6718a35383/out/platform_build/build
  running: "cmake" "--build" "." "--target" "install" "--config" "Debug" "--parallel" "16"
  Microsoft (R) Build Engine version 17.2.1+52cd2da31 for .NET Framework
  Copyright (C) Microsoft Corporation. All rights reserved.

    p8-platform.vcxproj -> C:\Users\nicky\Documents\crate_targets\debug\build\libcec-sys-e405de6718a35383\out\platform_build\build\Debug\p8-platform.lib
    -- Install configuration: "Debug"
    -- Up-to-date: C:/Users/nicky/Documents/crate_targets/debug/build/libcec-sys-e405de6718a35383/out/platform_build/lib/p8-platform.lib
    -- Up-to-date: C:/Users/nicky/Documents/crate_targets/debug/build/libcec-sys-e405de6718a35383/out/platform_build/include/p8-platform/os.h
    -- Up-to-date: C:/Users/nicky/Documents/crate_targets/debug/build/libcec-sys-e405de6718a35383/out/platform_build/include/p8-platform/windows/dlfcn-win
32.h
    -- Up-to-date: C:/Users/nicky/Documents/crate_targets/debug/build/libcec-sys-e405de6718a35383/out/platform_build/include/p8-platform/windows/os-socket
.h
    -- Up-to-date: C:/Users/nicky/Documents/crate_targets/debug/build/libcec-sys-e405de6718a35383/out/platform_build/include/p8-platform/windows/os-thread
s.h
    -- Up-to-date: C:/Users/nicky/Documents/crate_targets/debug/build/libcec-sys-e405de6718a35383/out/platform_build/include/p8-platform/windows/os-types.
h
    -- Up-to-date: C:/Users/nicky/Documents/crate_targets/debug/build/libcec-sys-e405de6718a35383/out/platform_build/include/p8-platform/sockets/cdevsocke
t.h
    -- Up-to-date: C:/Users/nicky/Documents/crate_targets/debug/build/libcec-sys-e405de6718a35383/out/platform_build/include/p8-platform/sockets/socket.h
    -- Up-to-date: C:/Users/nicky/Documents/crate_targets/debug/build/libcec-sys-e405de6718a35383/out/platform_build/include/p8-platform/sockets/tcp.h
    -- Up-to-date: C:/Users/nicky/Documents/crate_targets/debug/build/libcec-sys-e405de6718a35383/out/platform_build/include/p8-platform/threads/atomics.h
    -- Up-to-date: C:/Users/nicky/Documents/crate_targets/debug/build/libcec-sys-e405de6718a35383/out/platform_build/include/p8-platform/threads/mutex.h
    -- Up-to-date: C:/Users/nicky/Documents/crate_targets/debug/build/libcec-sys-e405de6718a35383/out/platform_build/include/p8-platform/threads/threads.h
    -- Up-to-date: C:/Users/nicky/Documents/crate_targets/debug/build/libcec-sys-e405de6718a35383/out/platform_build/include/p8-platform/util/atomic.h
    -- Up-to-date: C:/Users/nicky/Documents/crate_targets/debug/build/libcec-sys-e405de6718a35383/out/platform_build/include/p8-platform/util/buffer.h
    -- Up-to-date: C:/Users/nicky/Documents/crate_targets/debug/build/libcec-sys-e405de6718a35383/out/platform_build/include/p8-platform/util/StringUtils.
h
    -- Up-to-date: C:/Users/nicky/Documents/crate_targets/debug/build/libcec-sys-e405de6718a35383/out/platform_build/include/p8-platform/util/StdString.h
    -- Up-to-date: C:/Users/nicky/Documents/crate_targets/debug/build/libcec-sys-e405de6718a35383/out/platform_build/include/p8-platform/util/timeutils.h
    -- Up-to-date: C:/Users/nicky/Documents/crate_targets/debug/build/libcec-sys-e405de6718a35383/out/platform_build/include/p8-platform/util/util.h
    -- Up-to-date: C:/Users/nicky/Documents/crate_targets/debug/build/libcec-sys-e405de6718a35383/out/platform_build/lib/p8-platform/p8-platform-config.cm
ake
  cargo:root=C:/Users/nicky/Documents/crate_targets\debug\build\libcec-sys-e405de6718a35383\out\platform_build
  make platform
  cmake libcec
  CMAKE_TOOLCHAIN_FILE_x86_64-pc-windows-msvc = None
  CMAKE_TOOLCHAIN_FILE_x86_64_pc_windows_msvc = None
  HOST_CMAKE_TOOLCHAIN_FILE = None
  CMAKE_TOOLCHAIN_FILE = None
  CMAKE_GENERATOR_x86_64-pc-windows-msvc = None
  CMAKE_GENERATOR_x86_64_pc_windows_msvc = None
  HOST_CMAKE_GENERATOR = None
  CMAKE_GENERATOR = None
  CMAKE_PREFIX_PATH_x86_64-pc-windows-msvc = None
  CMAKE_PREFIX_PATH_x86_64_pc_windows_msvc = None
  HOST_CMAKE_PREFIX_PATH = None
  CMAKE_PREFIX_PATH = None
  CMAKE_x86_64-pc-windows-msvc = None
  CMAKE_x86_64_pc_windows_msvc = None
  HOST_CMAKE = None
  CMAKE = None
  running: "cmake" "C:/Users/nicky/Documents/crate_targets\\debug\\build\\libcec-sys-e405de6718a35383\\out\\vendor" "-G" "Visual Studio 17 2022" "-Thost=x
64" "-Ax64" "-DCMAKE_INSTALL_PREFIX=C:/Users/nicky/Documents/crate_targets\\debug\\build\\libcec-sys-e405de6718a35383\\out\\libcec_build" "-DCMAKE_C_FLAGS
= -nologo -MD -Brepro" "-DCMAKE_C_FLAGS_DEBUG= -nologo -MD -Brepro" "-DCMAKE_CXX_FLAGS= -nologo -MD -Brepro" "-DCMAKE_CXX_FLAGS_DEBUG= -nologo -MD -Brepro
" "-DCMAKE_ASM_FLAGS= -nologo -MD -Brepro" "-DCMAKE_ASM_FLAGS_DEBUG= -nologo -MD -Brepro" "-DCMAKE_BUILD_TYPE=Debug"
  -- Could NOT find PkgConfig (missing: PKG_CONFIG_EXECUTABLE)
  -- Could NOT find SWIG (missing: SWIG_EXECUTABLE SWIG_DIR)
  -- Configured features:
  -- Pulse-Eight CEC Adapter:                yes
  -- Pulse-Eight CEC Adapter detection:      yes
  -- xrandr support:                         no
  -- Raspberry Pi support:                   no
  -- TDA995x support:                        no
  -- Exynos support:                         no
  -- DRM support:                            no
  -- AOCEC support:                          no
  -- Python support:                         no
  -- lib info: , features: P8_USB, P8_detect
  -- Configuring done
  -- Generating done
  -- Build files have been written to: C:/Users/nicky/Documents/crate_targets/debug/build/libcec-sys-e405de6718a35383/out/libcec_build/build
  running: "cmake" "--build" "." "--target" "install" "--config" "Debug" "--parallel" "16"
  Microsoft (R) Build Engine version 17.2.1+52cd2da31 for .NET Framework
  Copyright (C) Microsoft Corporation. All rights reserved.

    CECClient.cpp
  C:\Program Files (x86)\Windows Kits\10\Include\10.0.22000.0\ucrt\corecrt.h(634,1): fatal error C1189: #error:  You cannot use 32-bit time_t (_USE_32BIT_
TIME_T) with _WIN64 [C:\Users\nicky\Documents\crate_targets\debug\build\libcec-sys-e405de6718a35383\out\libcec_build\build\src\libcec\cec.vcxproj]
    CECProcessor.cpp
  C:\Program Files (x86)\Windows Kits\10\Include\10.0.22000.0\ucrt\corecrt.h(634,1): fatal error C1189: #error:  You cannot use 32-bit time_t (_USE_32BIT_
TIME_T) with _WIN64 [C:\Users\nicky\Documents\crate_targets\debug\build\libcec-sys-e405de6718a35383\out\libcec_build\build\src\libcec\cec.vcxproj]
    LibCEC.cpp
  C:\Program Files (x86)\Windows Kits\10\Include\10.0.22000.0\ucrt\corecrt.h(634,1): fatal error C1189: #error:  You cannot use 32-bit time_t (_USE_32BIT_
TIME_T) with _WIN64 [C:\Users\nicky\Documents\crate_targets\debug\build\libcec-sys-e405de6718a35383\out\libcec_build\build\src\libcec\cec.vcxproj]
    LibCECC.cpp
  C:\Program Files (x86)\Windows Kits\10\Include\10.0.22000.0\ucrt\corecrt.h(634,1): fatal error C1189: #error:  You cannot use 32-bit time_t (_USE_32BIT_
TIME_T) with _WIN64 [C:\Users\nicky\Documents\crate_targets\debug\build\libcec-sys-e405de6718a35383\out\libcec_build\build\src\libcec\cec.vcxproj]
    LibCECDll.cpp
  C:\Program Files (x86)\Windows Kits\10\Include\10.0.22000.0\ucrt\corecrt.h(634,1): fatal error C1189: #error:  You cannot use 32-bit time_t (_USE_32BIT_
TIME_T) with _WIN64 [C:\Users\nicky\Documents\crate_targets\debug\build\libcec-sys-e405de6718a35383\out\libcec_build\build\src\libcec\cec.vcxproj]
    AdapterFactory.cpp
  C:\Program Files (x86)\Windows Kits\10\Include\10.0.22000.0\ucrt\corecrt.h(634,1): fatal error C1189: #error:  You cannot use 32-bit time_t (_USE_32BIT_
TIME_T) with _WIN64 [C:\Users\nicky\Documents\crate_targets\debug\build\libcec-sys-e405de6718a35383\out\libcec_build\build\src\libcec\cec.vcxproj]
    USBCECAdapterMessage.cpp
  C:\Program Files (x86)\Windows Kits\10\Include\10.0.22000.0\ucrt\corecrt.h(634,1): fatal error C1189: #error:  You cannot use 32-bit time_t (_USE_32BIT_
TIME_T) with _WIN64 [C:\Users\nicky\Documents\crate_targets\debug\build\libcec-sys-e405de6718a35383\out\libcec_build\build\src\libcec\cec.vcxproj]
    USBCECAdapterCommands.cpp
  C:\Program Files (x86)\Windows Kits\10\Include\10.0.22000.0\ucrt\corecrt.h(634,1): fatal error C1189: #error:  You cannot use 32-bit time_t (_USE_32BIT_
TIME_T) with _WIN64 [C:\Users\nicky\Documents\crate_targets\debug\build\libcec-sys-e405de6718a35383\out\libcec_build\build\src\libcec\cec.vcxproj]
    USBCECAdapterCommunication.cpp
  C:\Program Files (x86)\Windows Kits\10\Include\10.0.22000.0\ucrt\corecrt.h(634,1): fatal error C1189: #error:  You cannot use 32-bit time_t (_USE_32BIT_
TIME_T) with _WIN64 [C:\Users\nicky\Documents\crate_targets\debug\build\libcec-sys-e405de6718a35383\out\libcec_build\build\src\libcec\cec.vcxproj]
    USBCECAdapterMessageQueue.cpp
  C:\Program Files (x86)\Windows Kits\10\Include\10.0.22000.0\ucrt\corecrt.h(634,1): fatal error C1189: #error:  You cannot use 32-bit time_t (_USE_32BIT_
TIME_T) with _WIN64 [C:\Users\nicky\Documents\crate_targets\debug\build\libcec-sys-e405de6718a35383\out\libcec_build\build\src\libcec\cec.vcxproj]
    USBCECAdapterDetection.cpp
  C:\Program Files (x86)\Windows Kits\10\Include\10.0.22000.0\ucrt\corecrt.h(634,1): fatal error C1189: #error:  You cannot use 32-bit time_t (_USE_32BIT_
TIME_T) with _WIN64 [C:\Users\nicky\Documents\crate_targets\debug\build\libcec-sys-e405de6718a35383\out\libcec_build\build\src\libcec\cec.vcxproj]
    CECAudioSystem.cpp
  C:\Program Files (x86)\Windows Kits\10\Include\10.0.22000.0\ucrt\corecrt.h(634,1): fatal error C1189: #error:  You cannot use 32-bit time_t (_USE_32BIT_
TIME_T) with _WIN64 [C:\Users\nicky\Documents\crate_targets\debug\build\libcec-sys-e405de6718a35383\out\libcec_build\build\src\libcec\cec.vcxproj]
    CECBusDevice.cpp
  C:\Program Files (x86)\Windows Kits\10\Include\10.0.22000.0\ucrt\corecrt.h(634,1): fatal error C1189: #error:  You cannot use 32-bit time_t (_USE_32BIT_
TIME_T) with _WIN64 [C:\Users\nicky\Documents\crate_targets\debug\build\libcec-sys-e405de6718a35383\out\libcec_build\build\src\libcec\cec.vcxproj]
    CECDeviceMap.cpp
  C:\Program Files (x86)\Windows Kits\10\Include\10.0.22000.0\ucrt\corecrt.h(634,1): fatal error C1189: #error:  You cannot use 32-bit time_t (_USE_32BIT_
TIME_T) with _WIN64 [C:\Users\nicky\Documents\crate_targets\debug\build\libcec-sys-e405de6718a35383\out\libcec_build\build\src\libcec\cec.vcxproj]
    CECPlaybackDevice.cpp
  C:\Program Files (x86)\Windows Kits\10\Include\10.0.22000.0\ucrt\corecrt.h(634,1): fatal error C1189: #error:  You cannot use 32-bit time_t (_USE_32BIT_
TIME_T) with _WIN64 [C:\Users\nicky\Documents\crate_targets\debug\build\libcec-sys-e405de6718a35383\out\libcec_build\build\src\libcec\cec.vcxproj]
    CECRecordingDevice.cpp
  C:\Program Files (x86)\Windows Kits\10\Include\10.0.22000.0\ucrt\corecrt.h(634,1): fatal error C1189: #error:  You cannot use 32-bit time_t (_USE_32BIT_
TIME_T) with _WIN64 [C:\Users\nicky\Documents\crate_targets\debug\build\libcec-sys-e405de6718a35383\out\libcec_build\build\src\libcec\cec.vcxproj]
    CECTuner.cpp
  C:\Program Files (x86)\Windows Kits\10\Include\10.0.22000.0\ucrt\corecrt.h(634,1): fatal error C1189: #error:  You cannot use 32-bit time_t (_USE_32BIT_
TIME_T) with _WIN64 [C:\Users\nicky\Documents\crate_targets\debug\build\libcec-sys-e405de6718a35383\out\libcec_build\build\src\libcec\cec.vcxproj]
    CECTV.cpp
  C:\Program Files (x86)\Windows Kits\10\Include\10.0.22000.0\ucrt\corecrt.h(634,1): fatal error C1189: #error:  You cannot use 32-bit time_t (_USE_32BIT_
TIME_T) with _WIN64 [C:\Users\nicky\Documents\crate_targets\debug\build\libcec-sys-e405de6718a35383\out\libcec_build\build\src\libcec\cec.vcxproj]
    ANCommandHandler.cpp
  C:\Program Files (x86)\Windows Kits\10\Include\10.0.22000.0\ucrt\corecrt.h(634,1): fatal error C1189: #error:  You cannot use 32-bit time_t (_USE_32BIT_
TIME_T) with _WIN64 [C:\Users\nicky\Documents\crate_targets\debug\build\libcec-sys-e405de6718a35383\out\libcec_build\build\src\libcec\cec.vcxproj]
    CECCommandHandler.cpp
  C:\Program Files (x86)\Windows Kits\10\Include\10.0.22000.0\ucrt\corecrt.h(634,1): fatal error C1189: #error:  You cannot use 32-bit time_t (_USE_32BIT_
TIME_T) with _WIN64 [C:\Users\nicky\Documents\crate_targets\debug\build\libcec-sys-e405de6718a35383\out\libcec_build\build\src\libcec\cec.vcxproj]
    Generating Code...
    Compiling...
    SLCommandHandler.cpp
  C:\Program Files (x86)\Windows Kits\10\Include\10.0.22000.0\ucrt\corecrt.h(634,1): fatal error C1189: #error:  You cannot use 32-bit time_t (_USE_32BIT_
TIME_T) with _WIN64 [C:\Users\nicky\Documents\crate_targets\debug\build\libcec-sys-e405de6718a35383\out\libcec_build\build\src\libcec\cec.vcxproj]
    VLCommandHandler.cpp
  C:\Program Files (x86)\Windows Kits\10\Include\10.0.22000.0\ucrt\corecrt.h(634,1): fatal error C1189: #error:  You cannot use 32-bit time_t (_USE_32BIT_
TIME_T) with _WIN64 [C:\Users\nicky\Documents\crate_targets\debug\build\libcec-sys-e405de6718a35383\out\libcec_build\build\src\libcec\cec.vcxproj]
    RLCommandHandler.cpp
  C:\Program Files (x86)\Windows Kits\10\Include\10.0.22000.0\ucrt\corecrt.h(634,1): fatal error C1189: #error:  You cannot use 32-bit time_t (_USE_32BIT_
TIME_T) with _WIN64 [C:\Users\nicky\Documents\crate_targets\debug\build\libcec-sys-e405de6718a35383\out\libcec_build\build\src\libcec\cec.vcxproj]
    PHCommandHandler.cpp
  C:\Program Files (x86)\Windows Kits\10\Include\10.0.22000.0\ucrt\corecrt.h(634,1): fatal error C1189: #error:  You cannot use 32-bit time_t (_USE_32BIT_
TIME_T) with _WIN64 [C:\Users\nicky\Documents\crate_targets\debug\build\libcec-sys-e405de6718a35383\out\libcec_build\build\src\libcec\cec.vcxproj]
    RHCommandHandler.cpp
  C:\Program Files (x86)\Windows Kits\10\Include\10.0.22000.0\ucrt\corecrt.h(634,1): fatal error C1189: #error:  You cannot use 32-bit time_t (_USE_32BIT_
TIME_T) with _WIN64 [C:\Users\nicky\Documents\crate_targets\debug\build\libcec-sys-e405de6718a35383\out\libcec_build\build\src\libcec\cec.vcxproj]
    AQCommandHandler.cpp
  C:\Program Files (x86)\Windows Kits\10\Include\10.0.22000.0\ucrt\corecrt.h(634,1): fatal error C1189: #error:  You cannot use 32-bit time_t (_USE_32BIT_
TIME_T) with _WIN64 [C:\Users\nicky\Documents\crate_targets\debug\build\libcec-sys-e405de6718a35383\out\libcec_build\build\src\libcec\cec.vcxproj]
    adl-edid.cpp
  C:\Program Files (x86)\Windows Kits\10\Include\10.0.22000.0\ucrt\corecrt.h(634,1): fatal error C1189: #error:  You cannot use 32-bit time_t (_USE_32BIT_
TIME_T) with _WIN64 [C:\Users\nicky\Documents\crate_targets\debug\build\libcec-sys-e405de6718a35383\out\libcec_build\build\src\libcec\cec.vcxproj]
    nv-edid.cpp
  C:\Program Files (x86)\Windows Kits\10\Include\10.0.22000.0\ucrt\corecrt.h(634,1): fatal error C1189: #error:  You cannot use 32-bit time_t (_USE_32BIT_
TIME_T) with _WIN64 [C:\Users\nicky\Documents\crate_targets\debug\build\libcec-sys-e405de6718a35383\out\libcec_build\build\src\libcec\cec.vcxproj]
    drm-edid.cpp
  C:\Program Files (x86)\Windows Kits\10\Include\10.0.22000.0\ucrt\corecrt.h(634,1): fatal error C1189: #error:  You cannot use 32-bit time_t (_USE_32BIT_
TIME_T) with _WIN64 [C:\Users\nicky\Documents\crate_targets\debug\build\libcec-sys-e405de6718a35383\out\libcec_build\build\src\libcec\cec.vcxproj]
    os-edid.cpp
  C:\Program Files (x86)\Windows Kits\10\Include\10.0.22000.0\ucrt\corecrt.h(634,1): fatal error C1189: #error:  You cannot use 32-bit time_t (_USE_32BIT_
TIME_T) with _WIN64 [C:\Users\nicky\Documents\crate_targets\debug\build\libcec-sys-e405de6718a35383\out\libcec_build\build\src\libcec\cec.vcxproj]
    serialport.cpp
  C:\Program Files (x86)\Windows Kits\10\Include\10.0.22000.0\ucrt\corecrt.h(634,1): fatal error C1189: #error:  You cannot use 32-bit time_t (_USE_32BIT_
TIME_T) with _WIN64 [C:\Users\nicky\Documents\crate_targets\debug\build\libcec-sys-e405de6718a35383\out\libcec_build\build\src\libcec\cec.vcxproj]
    Generating Code...

  --- stderr
  CMake Deprecation Warning at CMakeLists.txt:3 (cmake_minimum_required):
    Compatibility with CMake < 2.8.12 will be removed from a future version of
    CMake.

    Update the VERSION argument <min> value or use a ...<max> suffix to tell
    CMake that the project does not need compatibility with older versions.


  make: *** No targets specified and no makefile found.  Stop.
  CMake Deprecation Warning at CMakeLists.txt:2 (cmake_minimum_required):
    Compatibility with CMake < 2.8.12 will be removed from a future version of
    CMake.

    Update the VERSION argument <min> value or use a ...<max> suffix to tell
    CMake that the project does not need compatibility with older versions.


  CMake Deprecation Warning at src/cec-client/CMakeLists.txt:2 (cmake_minimum_required):
    Compatibility with CMake < 2.8.12 will be removed from a future version of
    CMake.

    Update the VERSION argument <min> value or use a ...<max> suffix to tell
    CMake that the project does not need compatibility with older versions.


  CMake Deprecation Warning at src/cecc-client/CMakeLists.txt:2 (cmake_minimum_required):
    Compatibility with CMake < 2.8.12 will be removed from a future version of
    CMake.

    Update the VERSION argument <min> value or use a ...<max> suffix to tell
    CMake that the project does not need compatibility with older versions.


  CMake Deprecation Warning at src/pyCecClient/CMakeLists.txt:2 (cmake_minimum_required):
    Compatibility with CMake < 2.8.12 will be removed from a future version of
    CMake.

    Update the VERSION argument <min> value or use a ...<max> suffix to tell
    CMake that the project does not need compatibility with older versions.


  CMake Deprecation Warning at src/libcec/CMakeLists.txt:3 (cmake_minimum_required):
    Compatibility with CMake < 2.8.12 will be removed from a future version of
    CMake.

    Update the VERSION argument <min> value or use a ...<max> suffix to tell
    CMake that the project does not need compatibility with older versions.


  thread 'main' panicked at '
  command did not execute successfully, got: exit code: 1
```

### PR DESCRIPTION
**Pull request by ok-nick**
## Closes #13 
Support for Windows is fairly straightforward and libcec takes care of most of the work via their batch files.

### Prerequisites:
* Visual Studio 2019 w/ Desktop Development with C++ and Universal Windows Platform development
* CMake 3.12+
* Python 3.6+ with Debug Binaries (not sure the exact min version, took it from docs)
* **and possibly more**

### TODO
- [x] #14.
- [x] Initialize compiler env variables before smoke test.
- [x] Automatically choose between `Release` and `Debug` build.
- [x] Find platform type.
- [x] Add to CI.
- [x] Add to README.
- [x] Add to CHANGELOG.

For now, I've hardcoded a few parameters just for testing.

### CODE REVIEW

**Comment by ssalonen** [comment]
The idea of smoke test is to compile a small c application, including headers from cec project and linking to libcec shared library.

Note that intent is not utilize vendor library in any way here.

Even on linux this does not work by default, as the directories are not findable in the common distros without extra flags/environmental variables.

However, when setting those environment variables, it offers the user a viable option without pkg config (or without pkg config files). You can find concrete example from github CI flow where this is tested.

Are there similar same environment variables on windows? Is there precompiled distribution of libcec for windows?

**Comment by ssalonen** [comment]
Based on quick googling visual studio might utilize these directories and env variables 

- PATH for shared libs (dll)
- INCLUDE for headers https://docs.microsoft.com/en-us/cpp/preprocessor/hash-include-directive-c-cpp

If this is correct, it makes sense to keep the same smoke test with windows as well.

Is this something you can try out at some point? I am not sure how hard would it be to setup windows github action to test all this...

**Comment by ok-nick** [comment]
Yes, that sounds about right. The build script runs every compilation as to why I thought the smoke tests would fix it. There must be something in the `libcec` build script causing a file to be modified at the last second.

I'll have to check out the github actions once everything looks good.

**Comment by ok-nick** [comment]
I added a basic Windows test for vendored builds and it works well. The reason the `--release` flag was added to `cargo test` is because a debug build requires Python with debug binaries installed, which is not something github actions have by default.

I'm not sure what `cross` does or the point of using it in your situation, so I'm not sure if it is needed for CI on Windows?

**Comment by ssalonen** [comment]
I understand the issue without the --release. Ideally it would make sense not use --release as some of the rust assertions are not active then. 

On the other hand, there are no tests at all in libcec-sys, so it's not a big deal here, more of a topic for cec-rs.

Can we not compile the vendored build always as non-debug? I am not sure but is this how it goes with nix builds?
-------

Cross is not needed in windows here. In fact, it does not seem to support msvc, only gnu compiler https://github.com/cross-rs/cross

Cross is used for cross compiling and running the tests with different architectures. My thinking was that this library might be used with different type of embedded environments / devices, so why not introduce the  compilation check for it as well. However, since there is little platform specific code, it is not doing much now...

**Comment by ssalonen** [comment]
BTW, on windows, does this build the library as statically linked to the application binary? 

Should it? I am not sure which way is the preferred way on windows.

**Comment by ok-nick** [comment]
We could technically always compile libcec in release mode, although I'm assuming it may cancel out some of the debug assertions and other nice features. I guess the same also goes for Rust, so I'll add the correct python installation to CI.

As for Cross, if it is no longer useful, do you think we should remove it?

By default, [according to here](https://doc.rust-lang.org/rustc/command-line-arguments.html#option-l-link-lib), it will compile dynamically before statically. I don't see any use for a dynamic library, especially when everything Rust is pretty much compiled statically and upstream crates will probably expect this to just "work," so I'll add an explicit check.

**Comment by ok-nick** [comment]
I keep running into issues statically linking. When linking against `cec.lib`, it ends up linking back to `cec.dll`. When linking against `cec-static.lib`, it explodes with linking errors.

**Comment by ok-nick** [comment]
There is also no easy way to find installed Visual Studio versions. `cc` seems capable of this, but it only exposes a method for getting the latest installed version (if they have 2022 then we can't know if they have 2019), [check here](https://docs.rs/cc/latest/src/cc/windows_registry.rs.html#114).

An alternative would be to use the `vswhere` utility, which comes preinstalled with Visual Studio 2017+. Since `libcec` theoretically supports down to 2013, we would have to manually download the executable. In addition, we would have to pull in [this dependency](https://github.com/FaultyRAM/vswhere-rs), which unfortunately hasn't been maintained in over 4 years. I'm not sure if there is anything else.

**Comment by ssalonen** [comment]
When testing static linking, did you remove the cargo:rustc-link-lib=cec? I think it is the thing that adds the link?

**Comment by ok-nick** [comment]
No, I kept it as is and even tried changing it to `cec-static` as well as adding the explicit `static` kind as described in the docs.

**Comment by ok-nick** [comment]
You may be able to see for yourself if you fork my branch and run the CI. Tomorrow... well, later today for me, I could send u the output log I get.

**Comment by ssalonen** [comment]
Yes, I would expect static linking with windows while keeping dynamic linking with Linux. With Linux libcec is often easily available from distribution repos. 

We can always make this configurable as well, if need arises in the future.

**Comment by ssalonen** [comment]
> There is also no easy way to find installed Visual Studio versions. `cc` seems capable of this, but it only exposes a method for getting the latest installed version (if they have 2022 then we can't know if they have 2019), [check here](https://docs.rs/cc/latest/src/cc/windows_registry.rs.html#114).
> 
> 
> 
> An alternative would be to use the `vswhere` utility, which comes preinstalled with Visual Studio 2017+. Since `libcec` theoretically supports down to 2013, we would have to manually download the executable. In addition, we would have to pull in [this dependency](https://github.com/FaultyRAM/vswhere-rs), which unfortunately hasn't been maintained in over 4 years. I'm not sure if there is anything else.
> 
> Edit: Although `libcec` seems to compile fine with 2017, the docs state it only supports 2019+ so there could possibly be side effects. We should probably only support 2019 and if it's not installed, `libcec` will automatically output a corresponding error.

Was this resolved? Why is not ok to utilize the latest installed version?

**Comment by ssalonen** [comment]
Regarding cross:

On second thought it makes sense to ensure the build works, e.g. with arm (raspberry pi). This way we would get early failure already with libcec-sys, not with cec-rs, in case the build needs some adjustment.

With windows we are only looking at non-gnu compilation (not mingw), thus, cross is not usable there.

**Comment by ok-nick** [comment]
`libcec` does not compile with Visual Studio 2022. It does compile with 2017-2019 (as far as I've tested) although the docs state it only supports 2019+. I will make it so you must have 2019 installed.

**Comment by ok-nick** [comment]
Should definitely cache python, it takes 1-2 minutes to install.

**Comment by ssalonen** [comment]
Thank you! This has been quite some work but really great to see windows supported as well 🙏

**Review by ssalonen — CHANGES_REQUESTED** [review]
Review comments. Also, don't forget to update Readme (there is a statement on win support) and changelog

File: build/build.rs [hunk 1]
```diff
@@ -162,12 +168,40 @@ fn compile_vendored() {
...
+                "Release"
+            })
+            .arg("2019")
+            .arg(dst.join(LIBCEC_BUILD))
+            .arg("nmake")
+            .status()
+            .expect("failed to build libcec!");
+        println!(
+            "cargo:rustc-link-search=native={}",
+            dst.join(LIBCEC_BUILD).join("amd64").display()
```
[the remark this answers is not in the document]
Comment (ok-nick) [reply build/build.rs:194]: Yes

File: build/build.rs [hunk 2]
```diff
@@ -162,12 +168,40 @@ fn compile_vendored() {
...
+        );
+    } else {
+        compile_vendored_platform(&dst);
```
[the remark this answers is not in the document]
Comment (ok-nick) [reply build/build.rs:197]: I could also put it behind a `#[cfg(target_os = "linux")]` macro.

File: build/build.rs [hunk 3]
```diff
@@ -195,6 +229,7 @@ fn main() {
     println!("cargo:rerun-if-changed=vendor");
     println!("cargo:rerun-if-env-changed=LD_LIBRARY_PATH");
     println!("cargo:rerun-if-env-changed=LDFLAGS");
+    println!("cargo:rerun-if-env-changed=INCLUDE");
```
[the remark this answers is not in the document]
Comment (ok-nick) [reply build/build.rs:232]: Visual Studio sets env variables when `vsvarsall.bat` is ran, but that's automatically ran by `libcec`. I can't seem to find any indication of env variables being set on installation. The best we can do is check if the installation path exists although that doesn't seem possible with `cargo`.

File: build/build.rs [hunk 4]
```diff
@@ -162,12 +168,40 @@ fn compile_vendored() {
...
-    compile_vendored_platform(&dst);
-    compile_vendored_libcec(&dst);
-    println!(
-        "cargo:rustc-link-search=native={}",
-        dst.join(LIBCEC_BUILD).join("lib").display()
-    );
+    if cfg!(windows) {
+        println!("build libcec");
+        // All the compilation steps are combined into one command.
+        Command::new("cmd")
```
[the remark this answers is not in the document]
Comment (ok-nick) [reply build/build.rs:174]: `compile_vendored_libccec`*

File: build/build.rs [hunk 5]
```diff
@@ -13,6 +13,12 @@ const LIBCEC_BUILD: &str = "libcec_build";
 const PLATFORM_BUILD: &str = "platform_build";
 const LIBCEC_SRC: &str = "vendor";
 
+const ARCHITECTURE: &str = if cfg!(target_pointer_width = "64") {
```
Comment (ssalonen) [inline build/build.rs:16]: Should we move this windows specific constant to the windows build function (only place where it is used?)

I think it would avoid any confusion to reader as many more architectures are supported with Linux.

**Review by ssalonen — COMMENTED** [review]
One more final comment, then we are good to merge!

File: build/build.rs (hunk 5 above)
Comment (ok-nick) [reply build/build.rs:16]: I agree and I initially had that, but for [line 207](https://github.com/ok-nick/libcec-sys/blob/7fd8d96c2e3fed4ec32b0c4cb72190606badf546/build/build.rs#L207) we would then need to use individual blocks for each configuration.

We could also do two platform-specific variables right above the `println`. It's still not pretty, but better?

File: build/build.rs [hunk 6]
```diff
@@ -195,12 +234,16 @@ fn main() {
     println!("cargo:rerun-if-changed=vendor");
     println!("cargo:rerun-if-env-changed=LD_LIBRARY_PATH");
```
Comment (ok-nick) [inline build/build.rs:235]: I was thinking of creating a very simple macro for all the boilerplate, good idea?

File: build/build.rs (hunk 5 above)
Comment (ssalonen) [reply build/build.rs:16]: Allright, did not see line 207! I think we do not need `ARCHITECTURE` with linux so how about renaming simply as `ARCHITECTURE_WIN` for now?

File: build/build.rs (hunk 6 above)
Comment (ssalonen) [reply build/build.rs:235]: what would this macro do? what do you mean by the boilerplate in this context?

Comment (ok-nick) [reply build/build.rs:235]: Instead of `println!("cargo:rerun-if-env-changed=LD_LIBRARY_PATH");`, it could be `watch_env!("LD_LIBRARY_PATH");`

Comment (ssalonen) [reply build/build.rs:235]: Well there is a crate for it, https://docs.rs/cargo-emit/latest/cargo_emit/ (I stumbled on this while googling something)

Personally, I opted for not introducing additional dependency as the benefit is quite minimal (obfuscates the intent a bit, as the crate is not well known (?). My understanding is that println approach is fairly common in build scripts).

Comment (ok-nick) [reply build/build.rs:235]: I agree, it probably is best to leave it simple and clear. No need for fancy macros or pulling in another dependency.

File: build/build.rs (hunk 5 above)
Comment (ok-nick) [reply build/build.rs:16]: We could do that but imo it sounds a little hacky.. Maybe instead we could create a `link_libcec` function for Windows and Linux? That doesn't make it any less code, but it's definitely more clear and ergonomic for when more platforms are supported.

**Review by ssalonen — APPROVED** [review]

**Comment by ssalonen** [comment]
Big thank you!
